name:                brainskell
version:             0.1.0.0
github:              "willGuimont/brainskell"
license:             BSD3
author:              "William Guimont-Martin"
maintainer:          "William Guimont-Martin"
copyright:           "2019 William Guimont-Martin"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willGuimont/brainskell#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - array
  - mtl
  - parsec
  - monad-loops
  - containers
  - lens

library:
  source-dirs: src

executables:
  brainskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brainskell

tests:
  brainskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brainskell
